#!/bin/bash

action="$1"
role="$3"
csvlist="$5"

# run in background the previous startscript renamed as "background" for kubedirector
# to launch in parallel the startscript of all roles: head, worker-type-1 and worker-type-2.
# This sould solve the dead-lock met when the head starscript is not launched waiting for
# worker to complete their startscript that depend on the head not to be ready.

$(dirname "$0")/background &
