apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  name: jupyray
spec:
  label:
    name: Jupyray
    description: jupyter lab with ray client
  distroID: edrusb/ray
  version: '2.3.0'
  configSchemaVersion: 7
  defaultImageRepoTag: docker.io/edrusb/jupyray:2.3
  defaultConfigPackage:
    packageURL: file:///root/appconfig.tgz
  roles:
  - id: jupyterlab
    cardinality: '1'
    eventList:
    - "configure"
    - "addnodes"
    - "delnodes"
  services:
  - id: web
    label:
      name: "jupyter lab"
    endpoint:
      port: 8888
      isDashboard: True
      urlScheme: http
      hasAuthToken: True
  config:
    selectedRoles:
    - jupyterlab
    roleServices:
    - roleID: jupyterlab
      serviceIDs:
      - web
  capabilities:
  - SYS_RESOURCE
  - IPC_LOCK
  systemdRequired: false
